import { createPresentation, uid } from './store'

const o = (text: string, correct = false) => ({ id: uid('o_'), text, correct, image: null })
const m = (left: string, right: string) => ({ id: uid('m_'), left, right })
const it = (text: string) => ({ id: uid('i_'), text })
const base = { image: null, note: '', speedBonus: 'inherit', explain: { text: '', image: null } }

/** 建立一份涵蓋所有題型的示範簡報 */
export function seedDemo() {
  return createPresentation({
    title: 'Galgame 知識大挑戰（示範）',
    description: '涵蓋全部題型的範例簡報，可以直接播放或複製後修改。',
    theme: 'plum',
    settings: {
      speedBonus: true,
      showLeaderboard: true,
      allowLateJoin: true,
      qaEnabled: true,
      qaAnonymous: true,
      qaUpvote: true,
      qaModeration: false,
      reactionsEnabled: true,
    },
    // 表情符號要自己上傳圖片，這裡先留空
    reactions: [],
    slides: [
      {
        ...base,
        id: uid('s_'),
        type: 'content',
        title: 'Galgame 知識大挑戰',
        body: '用手機掃描 QR Code 加入，答對越快分數越高！\n\n共 8 題，包含單選、複選、是非、配對、順序、填空與開放問題。',
        timeLimit: 0,
        points: 'none',
        note: '開場白：歡迎大家，說明計分方式。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'single',
        title: '《CLANNAD》的女主角是誰？',
        options: [o('古河渚', true), o('神尾觀鈴'), o('美坂栞'), o('遠野美凪')],
        poll: false,
        timeLimit: 20,
        points: 'standard',
        explain: {
          text: '古河渚是《CLANNAD》的女主角，家裡經營「古河麵包店」。\n神尾觀鈴是《AIR》、美坂栞是《Kanon》、遠野美凪是《AIR》的角色 —— 三個都是 Key 社的作品，很容易混在一起。',
          image: null,
        },
      },
      {
        ...base,
        id: uid('s_'),
        type: 'truefalse',
        title: '「Galgame」一詞源自日文的「ギャルゲー」，意思是以與女性角色互動為主的遊戲。',
        options: [o('正確', true), o('錯誤')],
        poll: false,
        timeLimit: 15,
        points: 'standard',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'multi',
        title: '以下哪些作品是由 Key 社開發的？（可複選）',
        options: [o('AIR', true), o('CLANNAD', true), o('Fate/stay night'), o('Little Busters!', true), o('白色相簿2')],
        poll: false,
        timeLimit: 30,
        points: 'double',
        note: '複選題選錯會抵銷得分。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'match',
        title: '把作品和開發商配對起來',
        pairs: [
          m('CLANNAD', 'Key'),
          m('Fate/stay night', 'TYPE-MOON'),
          m('Steins;Gate', '5pb. / Nitroplus'),
          m('白色相簿2', 'Leaf / AQUAPLUS'),
        ],
        timeLimit: 60,
        points: 'double',
      },
      (() => {
        const key = uid('c_')
        const tm = uid('c_')
        const leaf = uid('c_')
        return {
          ...base,
          id: uid('s_'),
          type: 'categorize',
          title: '把這些作品拖進正確的開發商',
          categories: [
            { id: key, name: 'Key' },
            { id: tm, name: 'TYPE-MOON' },
            { id: leaf, name: 'Leaf / AQUAPLUS' },
          ],
          items: [
            { id: uid('i_'), text: 'CLANNAD', categoryId: key },
            { id: uid('i_'), text: 'AIR', categoryId: key },
            { id: uid('i_'), text: 'Fate/stay night', categoryId: tm },
            { id: uid('i_'), text: '月姬', categoryId: tm },
            { id: uid('i_'), text: 'To Heart', categoryId: leaf },
            { id: uid('i_'), text: '白色相簿2', categoryId: leaf },
          ],
          timeLimit: 60,
          points: 'double',
          note: '參與者用拖曳的把項目放進分類，放對幾個算幾分。',
        }
      })(),
      {
        ...base,
        id: uid('s_'),
        type: 'order',
        title: '把這些經典作品依「發售年份由早到晚」排序',
        items: [it('同級生（1992）'), it('To Heart（1997）'), it('AIR（2000）'), it('CLANNAD（2004）'), it('Steins;Gate（2009）')],
        timeLimit: 45,
        points: 'double',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'type',
        title: '《Steins;Gate》的主角叫什麼名字？（請輸入漢字全名）',
        accepted: ['岡部倫太郎', '冈部伦太郎', '鳳凰院凶真'],
        ignoreCase: true,
        ignoreSpace: true,
        timeLimit: 30,
        points: 'standard',
        note: '接受本名或中二病自稱。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'number',
        title: '《CLANNAD》最初的 PC 版是哪一年發售的？',
        answer: 2004,
        tolerance: 6,
        unit: '年',
        timeLimit: 30,
        points: 'standard',
        note: '猜越接近分數越高，差 6 年以上就沒分。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'list',
        title: '列出你知道的 Key 社作品（越多越好）',
        // 同一個答案的別名用 | 隔開，符合任一個就算命中這一組
        accepted: ['CLANNAD|克蘭納德', 'AIR', 'Kanon|カノン', 'Little Busters!|小小克星|LB', 'Rewrite', '智代 After'],
        allBonus: 0.5,
        maxSubmissions: 12,
        ignoreCase: true,
        ignoreSpace: true,
        timeLimit: 90,
        points: 'double',
        note: '答對越多分越高，全部答出再額外加分。別名可以用 | 隔開。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'soup',
        title: '猜猜這是哪部作品？',
        hints: [
          { text: '作品類型是廢萌作，但後半段會讓你哭到脫水' },
          { text: '開發商是 Key' },
          { text: '女主角家裡開麵包店' },
          { text: '有一句很有名的台詞：「團子、團子、團子大家族」' },
        ],
        stageSeconds: 20,
        accepted: ['CLANNAD', 'クラナド', '克蘭納德'],
        ignoreCase: true,
        ignoreSpace: true,
        timeLimit: 120,
        points: 'double',
        note: '提示一條一條給，越早猜中分數越高。答案可以設多組寫法。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'reveal',
        title: '這是哪個角色？',
        image: null,
        stages: 5,
        stageSeconds: 6,
        revealMode: 'tiles',
        options: [o('古河渚', true), o('神尾觀鈴'), o('美坂栞'), o('遠野美凪')],
        poll: false,
        timeLimit: 60,
        points: 'double',
        note: '請先在編輯器上傳要猜的 CG／立繪。越早階段猜中分數越高。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'music',
        title: '這是哪部作品的主題曲？',
        audio: null,
        audioStart: 0,
        autoPlay: true,
        options: [o('CLANNAD - 團子大家族', true), o('AIR - 鳥の詩'), o('Kanon - 風の辿り着く場所'), o('Little Busters! - Alicemagic')],
        poll: false,
        timeLimit: 45,
        points: 'standard',
        note: '請先在編輯器上傳音檔。音樂只在大螢幕播放。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'scale',
        title: '今天這場 Galgame quiz 你給幾分？',
        min: 1,
        max: 5,
        minLabel: '不太行',
        maxLabel: '超讚',
        timeLimit: 0,
        points: 'none',
        note: '評分題不計分，大螢幕會顯示平均與分布。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'open',
        title: '你心中的神作 Galgame 是哪一部？為什麼？',
        maxChars: 60,
        maxSubmissions: 2,
        display: 'cloud',
        timeLimit: 90,
        points: 'none',
        note: '回覆會即時變成文字雲。',
      },
      {
        ...base,
        id: uid('s_'),
        type: 'qa',
        title: '有什麼想問的嗎？',
        timeLimit: 0,
        points: 'none',
        note: '參與者可即時提問並互相按讚，按讚多的會排到前面。',
      },
    ],
  })
}
